version: "3.9"

services:
  web:
    build: .                  
    ports:
      - "5000:80"             
    depends_on:
      - redis                
    environment:
      - REDIS_HOST=redis      
    restart: always

  redis:
    image: redis:alpine       
    volumes:
      - redis_data:/data     

volumes:
  redis_data: